---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE, message=FALSE, results=FALSE, warning=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# Evaluation des rapports de SDD1
## Engels Guyliann & Grosjean Philippe

## Consignes générales

La date de remise des rapports pour ce cours est le **19 décembre 2018 à 23h59**. Les travaux seront téléchargés depuis github. Assurez-vous donc que l'ensemble de vos rapports soit complet et à jour. 

Après la reprise de l'ensemble des travaux, deux travaux seront corrigés parmi les travaux suivants :

- sdd1_biometry (travail de groupe)
- sdd1_coral_growth (travail individuel)
- sdd1_litterature (travail de groupe)
- sdd1_metagenomics (travail de groupe)
- sdd1_urchin_bio (travail individuel)
- sdd1_zooplankton (travail de groupe)

Un travail de groupe et un travail individuel seront sélectionnés et corrigés.

Chaque projet doit être :

- organisé : comprendre des dossiers cohérents (R, analysis, data)
    + Un script R doit se trouver dans le dossier R
    + Un fichier Rmd doit se trouver dans le dossier analysis
    + ...
    
- portable : chaque instruction (ligne de code) doit être exécutable depuis une autre machine virtuelle.

## Consignes pratiques par projet
### sdd1_biometry

Le projet portant sur la biomeérie doit donc contenir un ensemble de fichiers lié à l'analyse de la biométrie humaine (données obtenues via vos mesures personnelles). 

- Un R script pour préparer vos données provenant du web et les sauvegarder en local.
- Un fichier Rmd décrivant votre analyse comprennant 
    + introduction : Explication sur la thématique étudiée
    + matériels et méthodes : Explication sur la méthode d'acquisition des données et les outils d'analyses de ces données
    + but : Formulation de la question de recherche que vous vous posez sur la thématique
    + Résultats : 
        + partie descriptive des données (en lien avec votre question de recherche)
        + partie statistique des données (utilisation de un ou plusieurs tests statistiques adaptés sur votre question de recherche)
    + Discussion & Conclusion : Confrontation de vos analyses avec la bibliographie sur le sujet.

- Un fichier md structuré de maximum 1 page dans le dossier analysis comparant le workflow ‘classique’ en biologie (Microsoft Excel et Word) comparé à R et R Markdown

### sdd1_coral_growth

Le projet portant sur la croissance des coraux doit contenir :

- Un R script pour préparer vos données provenant du web et les sauvegarder en local.
- Un fichier Rmd décrivant votre analyse comprennant :
    + introduction : Explication sur la thématique étudiée (succint)
    + matériels et méthodes : (succint)
    + but : Formulation de la question de recherche que vous vous posez sur la thématique (succint)
    + Résultats : 
        + partie descriptive des données en tenant compte du remaniement des données demandées dans ce projet (en lien avec votre question de recherche) 
        
### sdd1_litterature

Le projet portant sur la littérature doit contenir : 

- Un fichier .md ou .Rmd de maximum 1 page expliquant la manière dont les articles scientifiques citent les analyses statistiques dans les différentes sections d'un article scientifique.

### sdd1-metagenomics

le projet portant sur la littérature doit contenir :

- Un fichier Rmd décrivant les données mises à votre disposition :
    + introduction : Explication sur la thématique étudiée (succint)
    + matériels et méthodes : (succint)
    + but : Formulation de la question de recherche que vous vous posez sur la thématique (succint)
    + Résultats : 
        + partie descriptive des données en tenant compte du remaniement des données demandées dans ce projets (en lien avec votre question de recherche) 

### sdd1_urchin_bio

Le projet portant sur la biométrie doit donc contenir un ensemble de fichiers lié à l'analyse de la biométrie des oursins. 

- Un fichier Rmd décrivant votre analyse comprenant 
    + introduction : Explication sur la thématique étudiée
    + matériels et méthodes : Explication sur la méthode d'acquisition des données et les outils d'analyses de ces données
    + but : Formulation de la question de recherche que vous vous posez sur la thématique
    + Résultats : 
        + partie descriptive des données (en lien avec votre question de recherche)
        + partie statistique des données (utilisation de un ou plusieurs tests statistique adaptés sur votre question de recheche)
    + Discussion & Conclusion : Confrontation de vos analyses avec la bibliographie sur le sujet.

### sdd1_zooplankton

Le projet portant sur l'analyse du zooplancton doit donc contenir : 

- Un fichier Rmd décrivant votre analyse comprennant 
    + introduction : Explication sur la thématique étudiée
    + matériels et méthodes : Explication sur la méthode d'acquisition des données et les outils d'analyses de ces données
    + but : Formulation de la question de recherche que vous vous posez sur la thématique
    + Résultats : 
        + partie descriptive des données (en lien avec votre question de recherche)
        + partie statistique des données (utilisation de un ou plusieurs tests statistiques adaptés sur votre question de recheche) sur les copépodes
    + Discussion & Conclusion : Confrontation de vos analyses avec la bibliographie sur le sujet.
    
Une analyse descriptive sur l'ensemble des données suivi d'une analyse plus précise sur "Poecilostomatoid", "Calanoid", "Cyclopoid", "Harpacticoid". Vous pouvez structurer votre analyse en deux fichiers.

## Remarques générales

### Choix des graphiques, des tableaux et des test statistiques 

L'ensemble des tests statistiques et des graphiques vu dans ce cours de SDD1, ne doivent pas se trouver dans chaque graphique. Vous devez avoir un regard critique sur vos analyses afin de proposer les graphiques, les tableaux et les analyses les plus pertinentes. 

### Le blog 

Le blog est évalué avec l'ensemble des learnr. 
