---
title: "Régression non-linéaire"
output: html_notebook
---

```{r setup}
SciViews::R
```

# Vitesse de réaction

```{r}
sp <- read("../data/speed_reaction.rds")
fm1 <- nls(speed ~ SSmicmen(conc, Vm, K), data = sp)
summary(fm1)
sp %>.%
  chart(data = ., speed ~ conc)+
  geom_point() +
  geom_line(f_aes(predict(fm1) ~ conc))
```

# Herbicides

```{r}
algae <- read("../data/algae.xlsx") 

chart(data = algae, vol ~ log(conc+1)) +
  geom_point() 


reg <- nls(vol ~ SSlogis(log(conc+1), Asym, xmid, scal), data = algae,
    trace = TRUE)
summary(reg)

reg1 <- nls(vol ~ SSfpl(log(conc+1), A, B,xmid, scal), data = algae,
    trace = TRUE)
summary(reg)

algae %>.%
  chart(data = ., vol ~ log(conc+1))+
  geom_point() +
  geom_line(f_aes(predict(reg) ~ log(conc+1)), color = "red") + 
  geom_line(f_aes(predict(reg1) ~ log(conc+1)), color = "blue")

AIC(reg, reg1)

algae %>.%
  chart(data = ., vol ~ log(conc+1))+
  geom_point() +
  geom_line(f_aes(predict(reg) ~ log(conc+1)), color = "red")
```

## Croissance de poacées

```{r}
ryegrass <- read("../data/ryegrass.csv")
#View(ryegrass)

ryegrass %>.%
  chart(data = ., rootl ~ log(conc+1)) +
  geom_point()

reg <- nls(rootl ~ SSlogis(log(conc+1), Asym, xmid, scal), data = ryegrass,
    trace = TRUE)
summary(reg)

# plot(rootl ~ log(conc+1), data = ryegrass)
# lines(log(ryegrass$conc+1), predict(reg))

reg1 <- nls(rootl ~ SSfpl(log(conc+1), A, B,xmid, scal), data = ryegrass,
    trace = TRUE)
summary(reg)

ryegrass %>.%
  chart(data = ., rootl ~ log(conc+1)) +
  geom_point() +
  geom_line(f_aes(predict(reg)~ log(conc + 1)), color = "red") +
  geom_line(f_aes(predict(reg1)~ log(conc + 1)), color = "blue")

AIC(reg, reg1)

ryegrass %>.%
  chart(data = ., rootl ~ log(conc+1)) +
  geom_point() +
  geom_line(f_aes(predict(reg1)~ log(conc + 1)), color = "blue")
```

## Croissance bactérienne

```{r}
growth <- read("../data/growth_curve.tsv")

growth %>.%
  chart(., growth_log ~ time) +
  geom_point()

reg_logis <- nls(growth_log ~ SSlogis(time, Asym, xmid, scal), data = growth, trace = TRUE)
summary(reg_logis)
reg_fpl <- nls(growth_log ~ SSfpl(time, A, B,xmid, scal), data = growth,
            trace = TRUE)
summary(reg_fpl)
reg_asymp <- nls(growth_log ~ SSasymp(time, Asym, R0, lrc), data = growth, trace = TRUE)
summary(reg_asymp)
reg_gomp <- nls(growth_log ~ SSgompertz(time, Asym, b2, b3), data = growth, trace = TRUE)
summary(reg_gomp)

CPCOLS <- c("#1f78b4", "#33a02c", "#e31a1c", "#FF7F00")

growth %>.%
  chart(., growth_log ~ time) +
  geom_point() +
  geom_line(f_aes(predict(reg_logis) ~ time), colour = CPCOLS[1]) +
  geom_line(f_aes(predict(reg_fpl) ~ time), colour = CPCOLS[2]) +
  geom_line(f_aes(predict(reg_asymp) ~ time), colour = CPCOLS[3]) +
  geom_line(f_aes(predict(reg_gomp) ~ time), colour = CPCOLS[4]) 

AIC(reg_logis, reg_fpl, reg_gomp, reg_asymp)

growth %>.%
  chart(., growth_log ~ time) +
  geom_point() +
  geom_line(f_aes(predict(reg_fpl) ~ time), colour = CPCOLS[2])  
```

## Croissance du tambour rouge

```{r}
reddrum <- read("reddrum", package = "UsingR")

reddrum %>.%
  chart(., length ~ age) +
  geom_point()

reg_asymp <- nls(length ~ SSasymp(age, Asym, R0, lrc), data = reddrum, trace = TRUE)
summary(reg_asymp)
reg_asymp_orig <- nls(length ~ SSasympOrig(age, Asym, lrc), data = reddrum,
                     trace = TRUE)
summary(reg_asymp_orig)

reddrum %>.%
  chart(., length ~ age) +
  geom_point() +
  geom_line(f_aes(predict(reg_asymp) ~ age), colour = CPCOLS[1]) +
  geom_line(f_aes(predict(reg_asymp_orig) ~ age), colour = CPCOLS[2])

AIC(reg_asymp, reg_asymp_orig) 

```



